module.exports =
    [
        {
            name: "Tommy Trojan",
            city: "Los Angeles",
            latitude: 34.020601,
            longitude: -118.285537,
            state: "California",
        },
        {
            name: "USC Village",
            city: "Los Angeles",
            latitude: 34.025394,
            longitude: -118.284184,
            state: "California",
        },
        {
            name: "Leavey Library",
            city: "Los Angeles",
            latitude: 34.021679,
            longitude: -118.282315,
            state: "California",
        },
        {
            name: "Lyon Center",
            city: "Los Angeles",
            latitude: 34.022670,
            longitude: -118.288234,
            state: "California",
        },
        {
            name: "McCarthy Quad",
            city: "Los Angeles",
            latitude: 34.021882,
            longitude: -118.285381,
            state: "California",
        },
        {
            name: "Bovard Auditorium",
            city: "Los Angeles",
            latitude: 34.020516,
            longitude: -118.285055,
            state: "California",
        },
        {
            name: "Ronald Tutor Campus Center",
            city: "Los Angeles",
            latitude: 34.020911,
            longitude: -118.285692,
            state: "California",
        },
        {
            name: "Annenberg School for Communication",
            city: "Los Angeles",
            latitude: 34.021537,
            longitude: -118.283176,
            state: "California",
        },
        {
            name: "Viterbi School of Engineering",
            city: "Los Angeles",
            latitude: 34.021983,
            longitude: -118.289113,
            state: "California",
        },
        {
            name: "Doheny Memorial Library",
            city: "Los Angeles",
            latitude: 34.020735,
            longitude: -118.284912,
            state: "California",
        },
        {
            name: "Cromwell Field and Track",
            city: "Los Angeles",
            latitude: 34.022745,
            longitude: -118.287541,
            state: "California",
        },
        {
            name: "Heritage Hall",
            city: "Los Angeles",
            latitude: 34.022501,
            longitude: -118.286258,
            state: "California",
        },
        {
            name: "USC Fisher Museum of Art",
            city: "Los Angeles",
            latitude: 34.020083,
            longitude: -118.282759,
            state: "California",
        },
        {
            name: "School of Cinematic Arts",
            city: "Los Angeles",
            latitude: 34.023031,
            longitude: -118.286056,
            state: "California",
        },
        {
            name: "USC Bookstore",
            city: "Los Angeles",
            latitude: 34.020973,
            longitude: -118.285566,
            state: "California",
        },
        {
            name: "Engemann Student Health Center",
            city: "Los Angeles",
            latitude: 34.024003,
            longitude: -118.289227,
            state: "California",
        },
        {
            name: "USC Galen Center",
            city: "Los Angeles",
            latitude: 34.020162,
            longitude: -118.287409,
            state: "California",
        },
        {
            name: "Marshall School of Business",
            city: "Los Angeles",
            latitude: 34.018593,
            longitude: -118.283912,
            state: "California",
        },
        {
            name: "USC International Academy",
            city: "Los Angeles",
            latitude: 34.019115,
            longitude: -118.284276,
            state: "California",
        },
        {
            name: "USC Shrine Auditorium",
            city: "Los Angeles",
            latitude: 34.024001,
            longitude: -118.287925,
            state: "California",
        },
            {
                name: "Hedco Neurosciences Building",
                city: "Los Angeles",
                latitude: 34.020145,
                longitude: -118.289734,
                state: "California",
            },
            {
                name: "Glorya Kaufman International Dance Center",
                city: "Los Angeles",
                latitude: 34.022801,
                longitude: -118.290481,
                state: "California",
            },
            {
                name: "USC Thornton School of Music",
                city: "Los Angeles",
                latitude: 34.022099,
                longitude: -118.288470,
                state: "California",
            },
            {
                name: "Parkside Apartments",
                city: "Los Angeles",
                latitude: 34.023799,
                longitude: -118.291299,
                state: "California",
            },
            {
                name: "University Church",
                city: "Los Angeles",
                latitude: 34.019483,
                longitude: -118.288994,
                state: "California",
            },
            {
                name: "Cale and Irani Residential College",
                city: "Los Angeles",
                latitude: 34.025707,
                longitude: -118.284765,
                state: "California",
            },
            {
                name: "Dr. Joseph Medicine Crow Center for International and Public Affairs",
                city: "Los Angeles",
                latitude: 34.020363,
                longitude: -118.283562,
                state: "California",
            },
            {
                name: "USC Roski School of Art and Design",
                city: "Los Angeles",
                latitude: 34.023251,
                longitude: -118.284039,
                state: "California",
            },
            {
                name: "USC Student Union",
                city: "Los Angeles",
                latitude: 34.020203,
                longitude: -118.284711,
                state: "California",
            },
            {
                name: "Kaprielian Hall",
                city: "Los Angeles",
                latitude: 34.021485,
                longitude: -118.287814,
                state: "California",
            }
        
]